import React, { useState, useEffect } from 'react';
import './MyRoster.css';

const MyRoster = ({ onBack }) => {
    const [shifts, setShifts] = useState([
        { id: 1, type: 'EARLY', vehicle: 'LDN 77X', date: 'Monday, Nov 12', time: '05:00 - 15:00' },
        { id: 2, type: 'LATE', vehicle: 'LDN 77X', date: 'Tuesday, Nov 13', time: '14:00 - 00:00' },
        { id: 3, type: 'STANDBY', vehicle: 'HQ POOL', date: 'Wednesday, Nov 14', time: 'ON CALL' },
        { id: 4, type: 'NIGHT', vehicle: 'LHR 99Z', date: 'Friday, Nov 16', time: '20:00 - 06:00' }
    ]);

    return (
        <div className="roster-view">
            <header className="roster-header">
                <button className="btn-close" onClick={onBack}>✖</button>
                <h2 className="text-gold">My Upcoming Roster</h2>
            </header>

            <div className="roster-list">
                {shifts.map(shift => (
                    <div className="shift-card" key={shift.id}>
                        <div className="shift-date">{shift.date}</div>
                        <div className="shift-details">
                            <span className={`shift-badge badge-${shift.type.toLowerCase()}`}>{shift.type}</span>
                            <span className="shift-time text-white font-mono">{shift.time}</span>
                            <span className="shift-vehicle text-muted font-bold">CAR: {shift.vehicle}</span>
                        </div>
                    </div>
                ))}
            </div>
            
            <div className="roster-footer text-center text-muted mt-m text-sm">
                Roster generated by VELO Autonomous Dispatch.
            </div>
        </div>
    );
};

export default MyRoster;
