-- ====================================================================================
-- VELO PLATFORM — MASTER INITIALIZATION SCHEMA (v2)
-- Strict Multi-Tenant Architecture · PostGIS Geospatial · Full Financial Engine
--
-- APPLY ORDER MATTERS: reference tables (tenants) are created before dependents.
-- Money convention: monetary columns are NUMERIC(12,2) storing GBP pounds unless the
-- column name carries a _pence suffix (integer pence). VAT is stored alongside NET.
--
-- Entity reference codes (Global Rule 3):
--   vehicles.reference_code  = 'VLO-XXXX'
--   drivers.reference_code   = '#V-XXXX'
-- ====================================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ------------------------------------------------------------------------------------
-- 1. MASTER MULTI-TENANCY CORE
-- ------------------------------------------------------------------------------------
CREATE TABLE tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(50) UNIQUE NOT NULL,                     -- human-readable short code
    name VARCHAR(150) NOT NULL,
    activation_status VARCHAR(50) NOT NULL DEFAULT 'REGISTRATION', -- REGISTRATION|ACTIVE|SUSPENDED|TERMINATED
    plan VARCHAR(50) NOT NULL DEFAULT 'STANDARD',
    preferred_language VARCHAR(10) DEFAULT 'en',
    vat_registered BOOLEAN NOT NULL DEFAULT FALSE,
    vat_number VARCHAR(50),
    finder_margin_rate NUMERIC(5,4) NOT NULL DEFAULT 0.2500,       -- B2B finder's margin (25% default)
    pool_accept_enabled BOOLEAN NOT NULL DEFAULT TRUE,             -- accepts pool jobs from others
    pool_min_price NUMERIC(10,2) NOT NULL DEFAULT 0.00,            -- acceptance filter: min price
    pool_vehicle_classes TEXT[] NOT NULL DEFAULT '{}',             -- acceptance filter: vehicle tiers
    pool_geo_center GEOMETRY(Point, 4326),                         -- acceptance filter: geography
    pool_geo_radius_m INT NOT NULL DEFAULT 50000,
    own_fleet_asap_timeout_s INT NOT NULL DEFAULT 60,              -- own-fleet-first window (ASAP)
    own_fleet_scheduled_timeout_m INT NOT NULL DEFAULT 10,         -- own-fleet-first window (scheduled)
    stripe_account_id VARCHAR(255),                                -- Stripe Connect express account
    stripe_payouts_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- White-label configuration generated by the Brand Identity wizard; consumed by mobile apps
CREATE TABLE white_label_configs (
    tenant_id UUID PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
    app_name VARCHAR(120),
    logo_url VARCHAR(512),
    splash_url VARCHAR(512),
    primary_color VARCHAR(9) NOT NULL DEFAULT '#D4AF37',
    background_color VARCHAR(9) NOT NULL DEFAULT '#0B0B0C',
    panel_color VARCHAR(9) NOT NULL DEFAULT '#1A1A1B',
    accent_color VARCHAR(9) NOT NULL DEFAULT '#D4AF37',
    custom_domain VARCHAR(255),
    firebase_google_app_id VARCHAR(255),
    firebase_ios_bundle VARCHAR(255),
    firebase_android_package VARCHAR(255),
    map_style_json JSONB,
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE operator_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    document_type VARCHAR(100) NOT NULL,
    file_url VARCHAR(512),
    extracted_data JSONB,
    verification_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',   -- PENDING|VERIFIED|REJECTED|REVIEW
    confidence_score DECIMAL(5,2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------------------------------
-- 2. PLATFORM SETTINGS (single persisted source of truth — §2 clearing fix, §4 Global Settings)
-- ------------------------------------------------------------------------------------
CREATE TABLE platform_settings (
    key VARCHAR(100) PRIMARY KEY,
    value JSONB NOT NULL,
    description VARCHAR(255),
    updated_by VARCHAR(100),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO platform_settings (key, value, description) VALUES
('fees', '{"mode":"CUSTOM_TRIP","vatRate":0.20,"creatorFeeNet":0,"fulfillerFeeDefaultNet":0}',
 'Fee configuration. mode is CUSTOM_TRIP: every trip price is manually entered per booking; no flat fee schedule exists platform-wide. VAT applies only to the platform fee extracted from drivers.'),
('network_floors', '{"EXECUTIVE":{"base":35.00,"perMile":2.10,"perHour":32.00,"minHours":2},"PREMIUM_MPV":{"base":85.00,"perMile":2.80,"perHour":45.00,"minHours":3},"FIRST_CLASS":{"base":85.00,"perMile":3.15,"perHour":56.00,"minHours":3},"ULTRA_LUXURY":{"base":175.00,"perMile":5.60,"perHour":105.00,"minHours":4}}',
 'Minimum wholesale price floors per vehicle tier: base + per-mile + per-hour x minimum-hours.'),
('negotiation', '{"timeoutMinutes":10}',
 'B2B pool counter-offer negotiation window in minutes.'),
('dispatch', '{"ownFleetAsapTimeoutSeconds":60,"ownFleetScheduledTimeoutMinutes":10,"nearbyDriverRadiusMeters":5000}',
 'Own-fleet-first acceptance windows and nearby-driver radius.'),
('payroll', '{"pensionRateDefault":0.05,"studentLoanRateDefault":0.09,"simplifiedNetPayDeductionRate":0.25}',
 'Payroll baseline deduction rates used for the simplified UK net-pay estimate.'),
('subscription', '{"weeklyFee":50.00}',
 'Velo subscription tier: £50.00/week, 0% commission while ACTIVE.')
;

-- ------------------------------------------------------------------------------------
-- 3. FLEET ASSET MANAGEMENT
-- ------------------------------------------------------------------------------------
CREATE TYPE vehicle_tier AS ENUM ('EXECUTIVE','PREMIUM_MPV','FIRST_CLASS','ULTRA_LUXURY');

CREATE TABLE vehicles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    reference_code VARCHAR(20) UNIQUE NOT NULL,          -- 'VLO-XXXX' display ID
    make VARCHAR(80) NOT NULL,
    model VARCHAR(80) NOT NULL,
    year INT,
    color VARCHAR(50),
    tier vehicle_tier NOT NULL DEFAULT 'EXECUTIVE',
    plate_number VARCHAR(20) NOT NULL,
    passenger_capacity INT NOT NULL DEFAULT 4,
    baggage_capacity INT NOT NULL DEFAULT 2,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',        -- ACTIVE|IN_SERVICE|MAINTENANCE|RETIRED
    current_odometer INT NOT NULL DEFAULT 0,
    mot_expiry DATE,
    phv_expiry DATE,                                     -- PCO / PHV licence
    insurance_expiry DATE,
    road_tax_expiry DATE,
    mot_document_url VARCHAR(512),
    insurance_document_url VARCHAR(512),
    photo_url VARCHAR(512),
    current_location GEOMETRY(Point, 4326),
    -- Lease tracking
    lease_provider VARCHAR(150),
    lease_start_date DATE,
    lease_end_date DATE,
    lease_total_cost NUMERIC(12,2),
    lease_paid_to_date NUMERIC(12,2) NOT NULL DEFAULT 0,
    monthly_finance_cost_pence INT NOT NULL DEFAULT 0,
    monthly_insurance_cost_pence INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_vehicles_tenant ON vehicles(tenant_id);
CREATE INDEX idx_vehicles_location ON vehicles USING GIST (current_location);

CREATE TABLE vehicle_assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    vehicle_id UUID NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
    driver_id UUID NOT NULL,                             -- FK added after drivers exists
    assigned_from TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_to TIMESTAMPTZ,
    is_primary BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TYPE maintenance_status AS ENUM ('OPEN','IN_PROGRESS','RESOLVED');

CREATE TABLE maintenance_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    vehicle_id UUID NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
    reported_by_driver_id UUID,
    reported_by_staff_id UUID,
    issue_description TEXT NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'LOW',         -- LOW|MEDIUM|HIGH|CRITICAL
    status maintenance_status NOT NULL DEFAULT 'OPEN',
    resolution_notes TEXT,
    resolution_amount NUMERIC(10,2),
    resolution_vat_inclusive BOOLEAN NOT NULL DEFAULT FALSE,
    reported_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ
);
CREATE INDEX idx_maintenance_vehicle ON maintenance_logs(vehicle_id);

CREATE TABLE fleet_general_expenses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    vehicle_id UUID NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
    driver_id UUID,
    expense_type VARCHAR(50) NOT NULL,                   -- FUEL|CARWASH|SERVICE|CUSTOM
    amount NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
    description TEXT,
    receipt_url VARCHAR(512),
    logged_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE odometer_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vehicle_id UUID NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
    driver_id UUID NOT NULL,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    reading INT NOT NULL,
    event_type VARCHAR(50) NOT NULL,                     -- START_SHIFT|END_SHIFT|MANUAL
    logged_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vehicle_issues (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vehicle_id UUID NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
    driver_id UUID NOT NULL,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    description TEXT NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'LOW',
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',          -- OPEN|ACKNOWLEDGED|FIXED
    reported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ
);

-- ------------------------------------------------------------------------------------
-- 4. CHAUFFEUR PERSONNEL HUB (Drivers)
-- ------------------------------------------------------------------------------------
CREATE TYPE payment_model AS ENUM ('COMMISSION','SALARIED','CUSTOM','SUBSCRIPTION');
CREATE TYPE subscription_status AS ENUM ('NONE','ACTIVE','PAST_DUE','CANCELLED');

CREATE TABLE drivers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),      -- primary/ employing tenant
    reference_code VARCHAR(20) UNIQUE NOT NULL,          -- '#V-XXXX' display ID
    firebase_uid VARCHAR(128) UNIQUE,
    fcm_token VARCHAR(512),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    photo_url VARCHAR(512),
    preferred_language VARCHAR(10) DEFAULT 'en',
    -- Pay framework (§1.1)
    payment_model payment_model NOT NULL DEFAULT 'COMMISSION',
    commission_rate NUMERIC(5,2),                        -- COMMISSION: driver keeps e.g. 80.00%
    hourly_rate NUMERIC(10,2),                           -- SALARIED
    trip_bonus NUMERIC(10,2),                            -- SALARIED: flat bonus per completed trip
    custom_pay_config JSONB,                             -- CUSTOM: dynamic admin-defined structure
    subscription_status subscription_status NOT NULL DEFAULT 'NONE',
    subscription_started_at TIMESTAMPTZ,
    subscription_renews_at TIMESTAMPTZ,
    weekly_subscription_fee NUMERIC(10,2) NOT NULL DEFAULT 50.00,
    -- Compliance & licensing
    license_number VARCHAR(80),
    license_expiry DATE,
    pco_badge_number VARCHAR(80),
    pco_badge_expiry DATE,
    pco_document_url VARCHAR(512),
    id_document_url VARCHAR(512),
    right_to_work_document_url VARCHAR(512),
    compliance_status VARCHAR(30) NOT NULL DEFAULT 'PENDING', -- PENDING|VERIFIED|EXPIRING|EXPIRED|SUSPENDED
    onboarding_status VARCHAR(30) NOT NULL DEFAULT 'STARTED', -- STARTED|DOCS_UPLOADED|IN_REVIEW|VERIFIED|REJECTED
    -- Profile
    status VARCHAR(30) NOT NULL DEFAULT 'OFFLINE',       -- ONLINE|ON_TRIP|OFFLINE|SUSPENDED
    average_rating NUMERIC(3,2) NOT NULL DEFAULT 5.00,
    jobs_completed INT NOT NULL DEFAULT 0,
    tenure_start_date DATE,
    notes TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_drivers_tenant ON drivers(tenant_id);
CREATE INDEX idx_drivers_firebase ON drivers(firebase_uid);

-- One unique DriverID, active under many TenantIDs (§1.3 multi-tenant membership)
CREATE TABLE driver_operator_memberships (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id UUID NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',        -- ACTIVE|SUSPENDED|LEFT
    payment_model payment_model,                         -- optional per-operator framework override
    commission_rate NUMERIC(5,2),
    hourly_rate NUMERIC(10,2),
    trip_bonus NUMERIC(10,2),
    custom_pay_config JSONB,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (driver_id, tenant_id)
);
CREATE INDEX idx_memberships_tenant ON driver_operator_memberships(tenant_id);

ALTER TABLE vehicle_assignments
    ADD CONSTRAINT fk_va_driver FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;

CREATE TABLE driver_locations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id UUID NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    vehicle_tier VARCHAR(50) NOT NULL DEFAULT 'EXECUTIVE',
    is_online BOOLEAN NOT NULL DEFAULT FALSE,
    current_location GEOMETRY(Point, 4326),
    bearing DECIMAL(5,2),
    speed DECIMAL(5,2),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX idx_driver_locations_driver ON driver_locations(driver_id);
CREATE INDEX idx_driver_locations_geom ON driver_locations USING GIST (current_location);

CREATE TABLE driver_shifts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    driver_id UUID NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
    vehicle_id UUID REFERENCES vehicles(id),
    clock_in TIMESTAMPTZ NOT NULL,
    clock_out TIMESTAMPTZ,
    total_hours NUMERIC(6,2),
    overtime_hours NUMERIC(6,2)
);
CREATE INDEX idx_driver_shifts_driver ON driver_shifts(driver_id);

-- Scheduling: continuous 24h roster at 30-minute granularity (§3 System Management)
CREATE TABLE staff (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    reference_code VARCHAR(20) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    role VARCHAR(80) NOT NULL DEFAULT 'DISPATCHER',      -- DISPATCHER|OPERATIONS_MANAGER|FINANCE|ADMIN
    department VARCHAR(80),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    photo_url VARCHAR(512),
    hire_date DATE,
    salary NUMERIC(10,2),
    shift_availability VARCHAR(80) DEFAULT 'Flexible',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE staff_shifts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    staff_id UUID NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
    -- 30-minute granularity slots; ISO date + start/end minutes-from-midnight (0..1440, % 30 = 0)
    shift_date DATE NOT NULL,
    start_minute INT NOT NULL CHECK (start_minute % 30 = 0 AND start_minute BETWEEN 0 AND 1410),
    duration_minutes INT NOT NULL CHECK (duration_minutes % 30 = 0 AND duration_minutes > 0),
    role_assignment VARCHAR(80),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (staff_id, shift_date, start_minute)
);
CREATE INDEX idx_staff_shifts_tenant_date ON staff_shifts(tenant_id, shift_date);

-- Chauffeur pre-booked roster (read by the driver app "My Roster" screen)
CREATE TABLE chauffeur_shifts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    driver_id UUID NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
    vehicle_id UUID REFERENCES vehicles(id),
    shift_type VARCHAR(20) NOT NULL DEFAULT 'STANDBY',   -- EARLY|LATE|NIGHT|STANDBY
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_chauffeur_shifts_driver ON chauffeur_shifts(driver_id);
CREATE INDEX idx_chauffeur_shifts_tenant ON chauffeur_shifts(tenant_id);

-- ------------------------------------------------------------------------------------
-- 5. CLIENTS — CORPORATE ACCOUNTS & BILLING + PRIVATE CLIENT REGISTRY (strictly separate)
-- ------------------------------------------------------------------------------------
CREATE TABLE corporate_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    reference_code VARCHAR(20) UNIQUE NOT NULL,
    company_name VARCHAR(200) NOT NULL,
    industry VARCHAR(120),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',        -- ACTIVE|SUSPENDED|CLOSED
    billing_email VARCHAR(255),
    billing_address TEXT,
    vat_number VARCHAR(50),
    purchase_order_required BOOLEAN NOT NULL DEFAULT FALSE,
    line_of_credit_limit NUMERIC(12,2),
    payment_terms_days INT NOT NULL DEFAULT 30,
    preferred_vehicle_tier vehicle_tier,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_corporate_accounts_tenant ON corporate_accounts(tenant_id);

CREATE TABLE corporate_authorized_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    corporate_account_id UUID NOT NULL REFERENCES corporate_accounts(id) ON DELETE CASCADE,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    booking_permission VARCHAR(20) NOT NULL DEFAULT 'FULL',  -- FULL|RESTRICTED
    cost_center VARCHAR(80),
    is_primary_contact BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE private_clients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    reference_code VARCHAR(20) UNIQUE NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    photo_url VARCHAR(512),
    tier VARCHAR(30) NOT NULL DEFAULT 'BLACK',           -- BLACK|GOLD|PLATINUM  (Velo Black default)
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    home_address TEXT,
    preferred_vehicle_tier vehicle_tier,
    dietary_constraints TEXT,
    cabin_constraints TEXT,
    temperature_preference VARCHAR(40),
    music_preference VARCHAR(80),
    privacy_level VARCHAR(20) NOT NULL DEFAULT 'STANDARD', -- STANDARD|GHOST
    vip_notes TEXT,                                      -- private notes, never exposed cross-tenant
    firebase_uid VARCHAR(128) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_private_clients_tenant ON private_clients(tenant_id);

CREATE TABLE saved_addresses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_type VARCHAR(20) NOT NULL CHECK (owner_type IN ('PRIVATE_CLIENT','CORPORATE_USER')),
    owner_id UUID NOT NULL,
    label VARCHAR(80) NOT NULL,
    address TEXT NOT NULL,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------------------------------
-- 6. TRIPS / JOBS — BOOKING LIFECYCLE, OWN-FLEET-FIRST, POOL, NEGOTIATION
-- ------------------------------------------------------------------------------------
CREATE TYPE trip_channel AS ENUM ('OWN_APP','POOL','CORPORATE');
CREATE TYPE trip_state AS ENUM (
    'PENDING_DISPATCH',      -- created, custom price set, not yet offered
    'OFFERING_OWN_FLEET',    -- own-fleet-first window active
    'IN_POOL',               -- dropped into shared cross-tenant pool
    'NEGOTIATION',           -- counter-offer countdown active
    'ASSIGNED',              -- accepted by a driver/tenant
    'DRIVER_EN_ROUTE',
    'ARRIVED',
    'IN_PROGRESS',
    'COMPLETED',
    'CANCELLED',
    'EXPIRED'
);
CREATE TYPE trip_cancellation_approver AS ENUM ('N/A','PENDING','ADMIN_APPROVED','ADMIN_REJECTED');

CREATE TABLE trips (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    task_id VARCHAR(30) UNIQUE NOT NULL,                 -- human display ID e.g. 'VLT-8F2K1'
    tenant_id UUID NOT NULL REFERENCES tenants(id),      -- originating tenant
    channel trip_channel NOT NULL DEFAULT 'OWN_APP',
    state trip_state NOT NULL DEFAULT 'PENDING_DISPATCH',
    -- Pricing (§1.2: fully custom-entered per trip; no flat fee schedule)
    custom_price NUMERIC(10,2) NOT NULL CHECK (custom_price > 0),
    pool_floor_price NUMERIC(10,2),                      -- computed network floor at publish time
    negotiated_price NUMERIC(10,2),                      -- active counter-offer amount
    final_price NUMERIC(10,2),
    platform_fee_net NUMERIC(10,2) NOT NULL DEFAULT 0,
    finder_margin_net NUMERIC(10,2) NOT NULL DEFAULT 0,  -- originating tenant's finder's margin
    driver_earnings NUMERIC(10,2),
    tip NUMERIC(10,2) NOT NULL DEFAULT 0,
    -- Route
    pickup_address TEXT NOT NULL,
    pickup_lat DOUBLE PRECISION,
    pickup_lng DOUBLE PRECISION,
    pickup_geom GEOMETRY(Point, 4326),
    dropoff_address TEXT NOT NULL,
    dropoff_lat DOUBLE PRECISION,
    dropoff_lng DOUBLE PRECISION,
    dropoff_geom GEOMETRY(Point, 4326),
    distance_miles NUMERIC(8,2),
    duration_minutes INT,
    -- Schedule
    booking_type VARCHAR(20) NOT NULL DEFAULT 'ASAP',    -- ASAP|SCHEDULED
    scheduled_at TIMESTAMPTZ,
    accepted_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    cancellation_reason VARCHAR(255),
    cancellation_approver trip_cancellation_approver NOT NULL DEFAULT 'N/A',
    -- Parties (§3 entity separation — never conflate)
    private_client_id UUID REFERENCES private_clients(id),
    corporate_account_id UUID REFERENCES corporate_accounts(id),
    corporate_booker_name VARCHAR(150),
    passenger_name VARCHAR(150) NOT NULL,
    passenger_phone VARCHAR(50),
    passenger_count INT NOT NULL DEFAULT 1 CHECK (passenger_count > 0),
    baggage_count INT NOT NULL DEFAULT 0 CHECK (baggage_count >= 0),
    requested_tier vehicle_tier,
    -- Fulfilment
    originating_tenant_id UUID NOT NULL REFERENCES tenants(id),
    fulfilling_tenant_id UUID REFERENCES tenants(id),
    driver_id UUID REFERENCES drivers(id),
    vehicle_id UUID REFERENCES vehicles(id),
    own_fleet_deadline TIMESTAMPTZ,                      -- own-fleet-first window expiry
    conflict_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    odometer_start INT,
    odometer_end INT,
    -- White-label display data snapshotted for cross-tenant cards (§1.3)
    originating_tenant_name VARCHAR(150),
    originating_tenant_logo_url VARCHAR(512),
    auto_pool_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_trips_tenant_state ON trips(tenant_id, state);
CREATE INDEX idx_trips_driver ON trips(driver_id);
CREATE INDEX idx_trips_pool ON trips(state) WHERE state IN ('IN_POOL','NEGOTIATION');
CREATE INDEX idx_trips_pickup_geom ON trips USING GIST (pickup_geom);
CREATE INDEX idx_trips_dropoff_geom ON trips USING GIST (dropoff_geom);

-- Own-fleet-first job offers to individual drivers (with per-driver expiry)
CREATE TABLE trip_offers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trip_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    driver_id UUID NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    offered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    response VARCHAR(20) NOT NULL DEFAULT 'PENDING',     -- PENDING|ACCEPTED|DECLINED|EXPIRED|FORFEITED_CONFLICT
    responded_at TIMESTAMPTZ
);
CREATE INDEX idx_trip_offers_driver ON trip_offers(driver_id, response);

-- B2B overflow pool mirror (jobs visible cross-tenant) + negotiation ledger
CREATE TYPE pool_job_state AS ENUM ('OPEN','NEGOTIATION','ALLOCATED','COMPLETED','WITHDRAWN');

CREATE TABLE b2b_pool_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trip_id UUID NOT NULL UNIQUE REFERENCES trips(id) ON DELETE CASCADE,
    originating_tenant_id UUID NOT NULL REFERENCES tenants(id),
    countering_tenant_id UUID REFERENCES tenants(id),
    pickup_location TEXT NOT NULL,
    pickup_geom GEOMETRY(Point, 4326) NOT NULL,
    dropoff_location TEXT NOT NULL,
    dropoff_geom GEOMETRY(Point, 4326) NOT NULL,
    vehicle_tier vehicle_tier NOT NULL,
    distance_miles NUMERIC(8,2),
    base_wholesale_fare NUMERIC(10,2) NOT NULL,
    current_wholesale_fare NUMERIC(10,2) NOT NULL,
    state pool_job_state NOT NULL DEFAULT 'OPEN',
    negotiation_deadline TIMESTAMPTZ,                    -- authoritative deadline (no in-memory timers)
    published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    allocated_at TIMESTAMPTZ
);
CREATE INDEX idx_pool_jobs_state ON b2b_pool_jobs(state);
CREATE INDEX idx_pool_jobs_pickup_geom ON b2b_pool_jobs USING GIST (pickup_geom);

CREATE TABLE pool_negotiations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pool_job_id UUID NOT NULL REFERENCES b2b_pool_jobs(id) ON DELETE CASCADE,
    proposing_tenant_id UUID NOT NULL REFERENCES tenants(id),
    proposed_fare NUMERIC(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',       -- PENDING|ACCEPTED|REJECTED|EXPIRED
    deadline TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ
);

-- ------------------------------------------------------------------------------------
-- 7. DRIVER DISPATCH CONFLICT ENGINE (§1.3)
-- ------------------------------------------------------------------------------------
CREATE TABLE schedule_conflicts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id UUID NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
    trip_a_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    trip_b_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    eta_delta_minutes INT,
    location_delta_miles NUMERIC(8,2),
    status VARCHAR(20) NOT NULL DEFAULT 'DETECTED',      -- DETECTED|RESOLVED_KEEP_A|RESOLVED_KEEP_B|AUTO_FORFEIT
    detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    forfeited_trip_id UUID
);

-- ------------------------------------------------------------------------------------
-- 8. FINANCIAL ENGINE — LEDGERS, ESCROW, INVOICES, PAYROLL, PAYOUTS
-- ------------------------------------------------------------------------------------
-- Driver-facing double-entry-ish journal: every credit/debit lands here
CREATE TABLE driver_ledgers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id UUID NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    trip_id UUID REFERENCES trips(id),
    entry_type VARCHAR(40) NOT NULL,
    -- TRIP_EARNINGS|TRIP_BONUS|TIP|PLATFORM_FEE|FINDER_MARGIN|SUBSCRIPTION_FEE|
    -- EXPENSE_PARKING|EXPENSE_TOLL|EXPENSE_AIRPORT_FEE|EXPENSE_CUSTOM|PAYROLL_DEDUCTION|ADJUSTMENT
    direction VARCHAR(6) NOT NULL CHECK (direction IN ('CREDIT','DEBIT')),
    amount NUMERIC(10,2) NOT NULL CHECK (amount > 0),
    description VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ledger_driver ON driver_ledgers(driver_id);
CREATE INDEX idx_ledger_tenant_time ON driver_ledgers(tenant_id, created_at);

-- Escrow lifecycle (Stripe Connect payment intents held per trip)
CREATE TYPE escrow_state AS ENUM ('HELD','RELEASED','REFUNDED','DISPUTED','FROZEN');

CREATE TABLE escrow_vault (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    held_amount NUMERIC(10,2) NOT NULL,
    released_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    state escrow_state NOT NULL DEFAULT 'HELD',
    stripe_payment_intent_id VARCHAR(255),
    stripe_charge_id VARCHAR(255),
    stripe_transfer_id VARCHAR(255),
    dispute_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX idx_escrow_booking ON escrow_vault(booking_id);

CREATE OR REPLACE FUNCTION prevent_frozen_payout()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.state = 'FROZEN' AND NEW.state = 'RELEASED' THEN
        RAISE EXCEPTION 'CRITICAL: Escrow record is FROZEN. Manual arbitration override required to release funds.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER check_frozen_escrow
    BEFORE UPDATE ON escrow_vault
    FOR EACH ROW
    EXECUTE FUNCTION prevent_frozen_payout();

-- Platform clearing ledger (B2B trades only): creator + fulfiller fees with VAT split
CREATE TABLE network_clearing_ledger (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID NOT NULL REFERENCES trips(id),
    originating_tenant_id UUID NOT NULL REFERENCES tenants(id),
    fulfilling_tenant_id UUID NOT NULL REFERENCES tenants(id),
    wholesale_fare NUMERIC(10,2) NOT NULL DEFAULT 0,
    creator_fee_net DECIMAL(10,2) NOT NULL DEFAULT 0,
    creator_fee_vat DECIMAL(10,2) NOT NULL DEFAULT 0,
    creator_fee_gross DECIMAL(10,2) NOT NULL DEFAULT 0,
    fulfiller_fee_net DECIMAL(10,2) NOT NULL DEFAULT 0,
    fulfiller_fee_vat DECIMAL(10,2) NOT NULL DEFAULT 0,
    fulfiller_fee_gross DECIMAL(10,2) NOT NULL DEFAULT 0,
    finder_margin_net DECIMAL(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE b2b_network_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID NOT NULL REFERENCES trips(id),
    originating_tenant_id UUID NOT NULL REFERENCES tenants(id),
    fulfilling_tenant_id UUID NOT NULL REFERENCES tenants(id),
    wholesale_fare DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Invoices (driver-linked per §2; also corporate billing invoices)
CREATE TABLE invoices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_number VARCHAR(40) UNIQUE NOT NULL,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    driver_id UUID REFERENCES drivers(id),
    corporate_account_id UUID REFERENCES corporate_accounts(id),
    trip_id UUID REFERENCES trips(id),
    customer_retail_fare DECIMAL(10,2) NOT NULL DEFAULT 0,  -- NEVER carries a VAT line (Rule 9)
    platform_fee_net DECIMAL(10,2) NOT NULL DEFAULT 0,
    platform_fee_vat DECIMAL(10,2) NOT NULL DEFAULT 0,
    driver_net_payout DECIMAL(10,2) NOT NULL DEFAULT 0,
    driver_vat_liability DECIMAL(10,2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'ISSUED',        -- DRAFT|ISSUED|PAID|OVERDUE|VOID
    due_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_invoices_tenant ON invoices(tenant_id);
CREATE INDEX idx_invoices_corporate ON invoices(corporate_account_id);

-- Payroll runs
CREATE TABLE payroll_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',         -- DRAFT|APPROVED|PAID
    created_by_staff_id UUID REFERENCES staff(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, period_start, period_end)
);

CREATE TABLE payroll_lines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    payroll_run_id UUID NOT NULL REFERENCES payroll_runs(id) ON DELETE CASCADE,
    driver_id UUID NOT NULL REFERENCES drivers(id),
    gross_pay NUMERIC(10,2) NOT NULL,
    pension_deduction NUMERIC(10,2) NOT NULL DEFAULT 0,
    student_loan_deduction NUMERIC(10,2) NOT NULL DEFAULT 0,
    other_deductions NUMERIC(10,2) NOT NULL DEFAULT 0,
    net_pay_estimate NUMERIC(10,2) NOT NULL,
    hours_worked NUMERIC(6,2),
    trips_completed INT NOT NULL DEFAULT 0,
    breakdown JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- Payout Hub
CREATE TABLE payouts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    driver_id UUID REFERENCES drivers(id),
    amount NUMERIC(10,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'GBP',
    method VARCHAR(30) NOT NULL DEFAULT 'STRIPE_CONNECT', -- STRIPE_CONNECT|MANUAL_BANK
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',        -- PENDING|PROCESSING|PAID|FAILED
    stripe_transfer_id VARCHAR(255),
    failure_reason TEXT,
    executed_by VARCHAR(100),
    executed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_payouts_tenant_status ON payouts(tenant_id, status);

-- Subscription ledger feed (worker writes weekly £50 debits here + driver_ledgers)
CREATE TABLE driver_subscriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id UUID NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    amount NUMERIC(10,2) NOT NULL DEFAULT 50.00,
    status VARCHAR(20) NOT NULL DEFAULT 'DUE',           -- DUE|PAID|FAILED
    paid_at TIMESTAMPTZ,
    failure_reason TEXT
);

-- Trip expenses logged by drivers (Post-Job Expense Modal)
CREATE TABLE booking_expenses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    driver_id UUID NOT NULL REFERENCES drivers(id),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    expense_type VARCHAR(50) NOT NULL,                   -- PARKING|TOLL|AIRPORT_FEE|CUSTOM
    amount NUMERIC(10,2) NOT NULL,
    custom_label TEXT,
    receipt_url VARCHAR(512),
    logged_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE driver_tips (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    driver_id UUID NOT NULL REFERENCES drivers(id),
    booking_id UUID NOT NULL REFERENCES trips(id),
    tip_amount DECIMAL(10,2) NOT NULL CHECK (tip_amount >= 0),
    cleared BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Ratings from pool jobs are private between the two tenants only (§1.3 Ghost Fulfilment)
CREATE TABLE trip_ratings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trip_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    rater_type VARCHAR(20) NOT NULL CHECK (rater_type IN ('PASSENGER','DRIVER')),
    stars INT NOT NULL CHECK (stars BETWEEN 1 AND 5),
    feedback TEXT,
    visibility VARCHAR(20) NOT NULL DEFAULT 'TENANTS_ONLY', -- PASSENGER_TRIP|TENANTS_ONLY
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------------------------------
-- 9. COMMS — NOTIFICATIONS, MESSAGING, TWILIO MASKED PROXY
-- ------------------------------------------------------------------------------------
CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES tenants(id),
    recipient_type VARCHAR(20) NOT NULL,                 -- DRIVER|TENANT_ADMIN|PASSENGER|STAFF
    recipient_id UUID,
    channel VARCHAR(20) NOT NULL,                        -- PUSH|SMS|EMAIL|IN_APP
    title VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    read_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_notifications_recipient ON notifications(recipient_type, recipient_id);

CREATE TABLE messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    thread_type VARCHAR(30) NOT NULL,                    -- DRIVER_DISPATCH|PASSENGER_MASKED|CLIENT_ENGAGEMENT
    thread_key VARCHAR(120) NOT NULL,                    -- e.g. trip task id / client ref
    trip_id UUID REFERENCES trips(id),
    sender_type VARCHAR(20) NOT NULL,                    -- DRIVER|DISPATCHER|PASSENGER|SYSTEM
    sender_id UUID,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_messages_thread ON messages(tenant_id, thread_type, thread_key);

-- Twilio masked-proxy call/SMS log (§1.3 Ghost Fulfilment — raw numbers never stored side-by-side)
CREATE TABLE proxy_contacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trip_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    twilio_proxy_service_sid VARCHAR(64),
    driver_proxy_number VARCHAR(30),
    passenger_proxy_number VARCHAR(30),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ
);

-- ------------------------------------------------------------------------------------
-- 10. COMPLIANCE DOCUMENTS & UPLOADS (AI verification pipeline)
-- ------------------------------------------------------------------------------------
CREATE TABLE compliance_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    entity_type VARCHAR(20) NOT NULL CHECK (entity_type IN ('DRIVER','VEHICLE','STAFF','TENANT')),
    entity_id UUID NOT NULL,
    document_type VARCHAR(60) NOT NULL,                  -- PCO_BADGE|MOT_CERT|INSURANCE|ID_DOCUMENT|RIGHT_TO_WORK|...
    file_url VARCHAR(512) NOT NULL,
    file_mime VARCHAR(80),
    ai_verification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING', -- PENDING|PROCESSING|VERIFIED|REJECTED|REVIEW
    ai_confidence DECIMAL(5,2),
    ai_extracted_data JSONB,
    ai_rejection_reason TEXT,
    expires_at DATE,
    uploaded_by VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_compliance_entity ON compliance_documents(entity_type, entity_id);

-- ------------------------------------------------------------------------------------
-- 11. TELEMETRY & PLATFORM HEALTH
-- ------------------------------------------------------------------------------------
CREATE TABLE telemetry_events (
    id BIGSERIAL PRIMARY KEY,
    tenant_id UUID,
    driver_id UUID,
    event_type VARCHAR(50) NOT NULL,                     -- GPS_PING|APP_HEALTH|API_LATENCY|GATEKEEPER_PHOTO
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_telemetry_type_time ON telemetry_events(event_type, recorded_at);

CREATE TABLE audit_logs (
    id BIGSERIAL PRIMARY KEY,
    actor_type VARCHAR(30) NOT NULL,
    actor_id VARCHAR(120),
    tenant_id UUID,
    action VARCHAR(120) NOT NULL,
    entity_type VARCHAR(60),
    entity_id VARCHAR(120),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    request_id VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Gatekeeper photos captured via camera in the Pre-Shift Gatekeeper (§5)
CREATE TABLE gatekeeper_checks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id UUID NOT NULL REFERENCES drivers(id),
    vehicle_id UUID NOT NULL REFERENCES vehicles(id),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    check_date DATE NOT NULL DEFAULT CURRENT_DATE,
    cleanliness_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    tyres_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    fuel_battery_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    rear_cabin_photo_url VARCHAR(512),
    passed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (driver_id, vehicle_id, check_date)
);

-- RLS baseline: tenant isolation on tenant-owned tables. The API sets
-- `SET LOCAL app.current_tenant_id` per request/transaction (see tenant.middleware.ts).
DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'vehicles','vehicle_assignments','maintenance_logs','fleet_general_expenses','odometer_logs',
        'vehicle_issues','drivers','driver_locations','driver_shifts','chauffeur_shifts','staff','staff_shifts',
        'corporate_accounts','private_clients','trips','driver_ledgers','invoices','escrow_vault',
        'payouts','booking_expenses','driver_tips','notifications','messages','payroll_runs',
        'compliance_documents','gatekeeper_checks'
    ]
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format(
            'CREATE POLICY tenant_isolation_policy ON %I USING (tenant_id = current_setting(''app.current_tenant_id'', true)::uuid)',
            t);
    END LOOP;
END $$;

-- b2b tables: both counterparties may see rows
ALTER TABLE b2b_pool_jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY pool_job_visibility_policy ON b2b_pool_jobs
    USING (
        originating_tenant_id = current_setting('app.current_tenant_id', true)::uuid
        OR countering_tenant_id = current_setting('app.current_tenant_id', true)::uuid
        OR (state = 'OPEN' AND current_setting('app.current_tenant_id', true)::uuid IS NOT NULL)
    );

ALTER TABLE b2b_network_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY b2b_tenant_isolation_policy ON b2b_network_transactions
    USING (
        originating_tenant_id = current_setting('app.current_tenant_id', true)::uuid
        OR fulfilling_tenant_id = current_setting('app.current_tenant_id', true)::uuid
    );

ALTER TABLE network_clearing_ledger ENABLE ROW LEVEL SECURITY;
CREATE POLICY b2b_ledger_isolation_policy ON network_clearing_ledger
    USING (
        originating_tenant_id = current_setting('app.current_tenant_id', true)::uuid
        OR fulfilling_tenant_id = current_setting('app.current_tenant_id', true)::uuid
    );

-- platform_settings / white_label_configs / tenants / audit_logs / telemetry_events: platform-admin
-- scope is enforced in the API layer (admin key), not RLS.

-- ------------------------------------------------------------------------------------
-- 11c. SELF-HOSTED AUTH (Jawa Ride pattern) — replaces Firebase Auth entirely.
-- bcrypt password hashes, refresh-token rotation, and OTP codes all live in our
-- own PostgreSQL. Social tokens (Google/Apple) are verified server-side against
-- the issuer and mapped onto these same identities.
-- ------------------------------------------------------------------------------------
CREATE TABLE auth_identities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    actor_type VARCHAR(20) NOT NULL CHECK (actor_type IN ('DRIVER', 'PRIVATE_CLIENT')),
    actor_id UUID NOT NULL,                              -- drivers.id | private_clients.id (no FK: created after identity)
    provider VARCHAR(20) NOT NULL CHECK (provider IN ('PASSWORD', 'PHONE', 'GOOGLE', 'APPLE')),
    subject VARCHAR(128) NOT NULL,                       -- email (lowercased) for PASSWORD, provider 'sub' for social
    password_hash VARCHAR(255),                          -- PASSWORD only, bcrypt
    display_name VARCHAR(150),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider, subject)
);
CREATE INDEX idx_auth_identities_actor ON auth_identities(actor_type, actor_id);

CREATE TABLE auth_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    identity_id UUID NOT NULL REFERENCES auth_identities(id) ON DELETE CASCADE,
    refresh_token_hash VARCHAR(128) NOT NULL,            -- sha-256 of the rotating refresh token
    user_agent VARCHAR(255),
    ip_address VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_refreshed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ
);
CREATE INDEX idx_auth_sessions_identity ON auth_sessions(identity_id);

CREATE TABLE auth_otp_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    phone VARCHAR(50) NOT NULL,
    code_hash VARCHAR(128) NOT NULL,                     -- sha-256, never store the raw code
    purpose VARCHAR(20) NOT NULL DEFAULT 'LOGIN',        -- LOGIN | BIND
    attempts INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 5,
    consumed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_auth_otp_phone ON auth_otp_codes(phone, purpose);

-- ------------------------------------------------------------------------------------
-- 12. SEED: platform demo tenant (used for local/e2e smoke; production tenants onboard via backoffice)
-- ------------------------------------------------------------------------------------
INSERT INTO tenants (id, code, name, activation_status, vat_registered, contact_email)
VALUES ('00000000-0000-0000-0000-000000000001', 'VELO-HQ', 'Velo Executive HQ', 'ACTIVE', TRUE, 'ops@veloexecutive.co.uk')
ON CONFLICT (code) DO NOTHING;

INSERT INTO white_label_configs (tenant_id, app_name, primary_color, background_color, panel_color)
VALUES ('00000000-0000-0000-0000-000000000001', 'Velo Executive', '#D4AF37', '#0B0B0C', '#1A1A1B')
ON CONFLICT (tenant_id) DO NOTHING;
