import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#000' },
  drawerContainer: { flex: 1, flexDirection: 'row', backgroundColor: '#000' },
  sidebar: { width: 280, backgroundColor: '#111', paddingTop: 60, paddingHorizontal: 20 },
  mainContent: { flex: 1, backgroundColor: '#000' },
  closeSidebarBtn: { alignSelf: 'flex-end', marginBottom: 20 },
  sidebarMenuItem: { paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: '#222' },
  sidebarMenuText: { color: '#EAEAEA', fontSize: 18, letterSpacing: 1 },
  sidebarActiveMenuText: { color: '#D4AF37', fontWeight: 'bold' },
  topNav: { height: 60, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, borderBottomWidth: 1, borderBottomColor: '#1A1A1A' },
  hamburgerBtn: { padding: 10 },
  hamburgerText: { color: '#EAEAEA', fontSize: 24 },
  navTitle: { color: '#D4AF37', fontSize: 20, fontWeight: 'bold', letterSpacing: 2 },
  statusPill: { backgroundColor: '#131F17', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12, borderWidth: 1, borderColor: '#34C759' },
  statusText: { color: '#34C759', fontSize: 12, fontWeight: 'bold' },
  workspaceCanvas: { flex: 1, position: 'relative' },
  radarPoolContainer: { padding: 20, paddingBottom: 100 },
  manifestCard: { backgroundColor: '#111', borderRadius: 12, padding: 20, marginBottom: 20, borderWidth: 1, borderColor: '#222' },
  manifestHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  timePill: { backgroundColor: '#1A1A1A', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6 },
  timeText: { color: '#D4AF37', fontWeight: 'bold' },
  serviceLevelPill: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4, borderWidth: 1, borderColor: '#D4AF37' },
  serviceLevelText: { color: '#D4AF37', fontSize: 10, fontWeight: 'bold' },
  routeBlock: { borderLeftWidth: 2, borderLeftColor: '#333', paddingLeft: 15, marginLeft: 5, marginBottom: 20 },
  locationNode: { marginBottom: 15 },
  locationLabel: { color: '#666', fontSize: 10, fontWeight: 'bold', letterSpacing: 1, marginBottom: 4 },
  locationValue: { color: '#EAEAEA', fontSize: 16 },
  paxRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  paxInitials: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#222', justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  paxInitialsText: { color: '#D4AF37', fontWeight: 'bold' },
  paxName: { color: '#EAEAEA', fontSize: 16, fontWeight: 'bold' },
  paxSub: { color: '#888', fontSize: 12 },
  takeoverButton: { backgroundColor: '#D4AF37', height: 50, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  takeoverButtonText: { color: '#000', fontWeight: 'bold', fontSize: 16, letterSpacing: 1 },
  takeoverModalOverlay: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', alignItems: 'center', zIndex: 100 },
  takeoverModalContent: { width: '90%', backgroundColor: '#111', borderRadius: 16, padding: 25, borderWidth: 1, borderColor: '#333' },
  takeoverTitle: { color: '#FFF', fontSize: 22, fontWeight: 'bold', textAlign: 'center', marginBottom: 10 },
  takeoverSubtitle: { color: '#888', textAlign: 'center', marginBottom: 30 },
  countdownCircle: { width: 80, height: 80, borderRadius: 40, borderWidth: 4, borderColor: '#D4AF37', alignSelf: 'center', justifyContent: 'center', alignItems: 'center', marginBottom: 30 },
  countdownText: { color: '#D4AF37', fontSize: 24, fontWeight: 'bold' },
  acknowledgeButton: { backgroundColor: '#D4AF37', height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', marginBottom: 15 },
  acknowledgeButtonText: { color: '#000', fontWeight: 'bold', fontSize: 16, letterSpacing: 1 },
  rejectButton: { height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#333' },
  rejectButtonText: { color: '#888', fontWeight: 'bold', fontSize: 16 },
  activeRideExecutionSheet: { flex: 1, padding: 20 },
  pulsingWarningHeader: { color: '#D4AF37', fontSize: 20, fontWeight: 'bold', letterSpacing: 2, textAlign: 'center', marginBottom: 5 },
  tenantOriginatorLabel: { color: '#888', textAlign: 'center', fontSize: 12, letterSpacing: 1, marginBottom: 25 },
  shiftMetricsGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 25 },
  metricBlock: { flex: 1, backgroundColor: '#111', padding: 15, borderRadius: 8, marginHorizontal: 5, borderWidth: 1, borderColor: '#222', alignItems: 'center' },
  metricLabelText: { color: '#666', fontSize: 10, fontWeight: 'bold', letterSpacing: 1, marginBottom: 5 },
  metricValueText: { color: '#EAEAEA', fontSize: 18, fontWeight: 'bold' },
  requestedTimeSolidBox: { backgroundColor: '#111', padding: 15, borderRadius: 8, borderWidth: 1, borderColor: '#222', alignItems: 'center', marginBottom: 25 },
  timeBoxLabel: { color: '#666', fontSize: 10, fontWeight: 'bold', letterSpacing: 1, marginBottom: 5 },
  timeBoxValueBold: { color: '#EAEAEA', fontSize: 20, fontWeight: 'bold' },
  mapPlaceholderContainer: { height: 200, backgroundColor: '#111', borderRadius: 12, marginBottom: 25, borderWidth: 1, borderColor: '#222', overflow: 'hidden' },
  pagingCardShortcut: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 15, backgroundColor: '#1A1A1A', borderRadius: 8, borderWidth: 1, borderColor: '#333', marginTop: 15 },
  pagingShortcutText: { color: '#D4AF37', fontSize: 12, fontWeight: 'bold', letterSpacing: 1 },
  landscapePagingBoard: { flex: 1, backgroundColor: '#000', justifyContent: 'center', alignItems: 'center' },
  tenantWatermark: { color: '#1A1A1A', fontSize: 100, fontWeight: 'bold', position: 'absolute', top: '30%' },
  paxPagingName: { color: '#FFF', fontSize: 80, fontWeight: 'bold', textAlign: 'center', zIndex: 10 },
  paxPagingFlight: { color: '#D4AF37', fontSize: 30, marginTop: 20, letterSpacing: 4, zIndex: 10 },
  closePagingBtn: { position: 'absolute', top: 40, right: 40, padding: 20, backgroundColor: '#111', borderRadius: 40, borderWidth: 1, borderColor: '#333' },
  inputLabelField: { color: '#666', fontSize: 12, fontWeight: 'bold', letterSpacing: 1, marginBottom: 10, marginTop: 10 },
  customFieldInputBox: { backgroundColor: '#111', borderRadius: 8, borderWidth: 1, borderColor: '#333', color: '#FFF', paddingHorizontal: 15, height: 50, fontSize: 16 },
  presetExpensePill: { backgroundColor: '#111', borderRadius: 20, borderWidth: 1, borderColor: '#333', paddingHorizontal: 15, paddingVertical: 8, marginRight: 10, marginBottom: 10 },
  presetText: { color: '#EAEAEA', fontSize: 14 },
  emergencyCancelBtnText: { color: '#FF3B30', fontSize: 12, fontWeight: 'bold', letterSpacing: 1 },
  takeoverEmergencyCancelBtn: { marginTop: 20, alignItems: 'center' },
  executionEmergencyCancelBtn: { marginTop: 30, alignItems: 'center', padding: 15, backgroundColor: '#1F1314', borderRadius: 8, borderWidth: 1, borderColor: '#3A1515' },
  countdownValueDisplayText: { color: '#FF3B30', fontSize: 16, fontWeight: 'bold', textAlign: 'center', marginVertical: 10 },
  independentCancelButton: { backgroundColor: '#1F1314', padding: 15, borderRadius: 8, borderWidth: 1, borderColor: '#FF3B30', alignItems: 'center' },
  independentCancelButtonText: { color: '#FF3B30', fontWeight: 'bold', fontSize: 14, letterSpacing: 1 }
});
