require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'
prepare_react_native_project!

target 'VeloDriverApp' do
  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => true
  )
end

post_install do |installer|
  react_native_post_install(installer)
end
